# Generated by Django 5.0.2 on 2024-02-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_rename_status_todo_completed_remove_todo_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='name',
            new_name='description',
        ),
    ]
